#include <QApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSaveFile>
#include <QTimer>
#include <functional>

#include "orbital/atomic_orbital.hpp"
#include "ui/atomic_orbital_widget.hpp"

namespace {
/** @brief Writes a generated atlas file and reports filesystem failures. */
bool write_atlas_file(const QString& path, const QByteArray& bytes) {
  QSaveFile file(path);
  if (!file.open(QIODevice::WriteOnly) || file.write(bytes) != bytes.size() || !file.commit()) {
    qCritical().noquote() << "could not write" << path << file.errorString();
    return false;
  }
  return true;
}

/** @brief Renders both poster layouts and matching definitions for the complete catalog. */
int generate_atlas(QApplication& application, const QString& output_path) {
  QDir output(output_path);
  if (!QDir().mkpath(output.absolutePath())) return 2;
  // An interrupted regeneration must not advertise a complete atlas to LaTeX.
  for (const QString& marker : {QStringLiteral("catalog.tex"), QStringLiteral("manifest.json")}) {
    const QString path = output.filePath(marker);
    if (QFile::exists(path) && !QFile::remove(path)) {
      qCritical().noquote() << "could not invalidate atlas marker" << path;
      return 1;
    }
  }
  AtomicOrbitalWidget widget;
  widget.resize(1600, 800);
  widget.show();
  application.processEvents();
  QByteArray catalog("% Generated by atomic_orbital_preview_generator --atlas.\n");
  QJsonArray entries;
  for (const auto& orbital : atomic_orbital_catalog()) {
    // A family-dependent oblique view avoids looking along an angular node.
    const QString plane = orbital.l == 0  ? QStringLiteral("xy")
                          : orbital.m < 0 ? QStringLiteral("yz")
                                          : QStringLiteral("xz");
    catalog += QStringLiteral("\\uilorbitalentry{%1}{%2}{%3}{%4}{%5}\n")
                   .arg(orbital.name, orbital.label)
                   .arg(orbital.n - orbital.l - 1)
                   .arg(orbital.l)
                   .arg(orbital.l == 0 && orbital.n > 1 ? QStringLiteral("cutaway")
                                                        : QStringLiteral("isosurface"))
                   .toUtf8();
    for (const QString& palette : {QStringLiteral("garnet_slate"), QStringLiteral("garnet_teal")}) {
      const QString negative = palette == QStringLiteral("garnet_slate")
                                   ? QStringLiteral("#426B86")
                                   : QStringLiteral("#177E72");
      const QJsonObject payload{
          {"format", "uil.atomic-orbital"},
          {"version", 1},
          {"title", QStringLiteral("Hydrogen-like $%1$ orbital").arg(orbital.label)},
          {"orbital", orbital.name},
          {"surface", QJsonObject{{"positive_color", "#8E1B3E"},
                                  {"negative_color", negative},
                                  {"grid_size", 81},
                                  {"isovalue", 0.0}}},
          {"sampling_plane",
           QJsonObject{{"type", plane},
                       {"offset", QJsonObject{{"min", -1.0}, {"max", 1.0}, {"value", 0.0}}}}},
          {"contour", QJsonObject{{"colormap", palette}, {"maximum", 0.1}, {"levels", 12}}}};
      const QByteArray bytes = QJsonDocument(payload).toJson();
      AtomicOrbitalDefinition definition;
      QString error;
      if (!parse_atomic_orbital(bytes, &definition, &error)) {
        qCritical().noquote() << error;
        return 1;
      }
      const QString directory = output.filePath(palette);
      if (!QDir().mkpath(directory)) return 1;
      const QString stem = QDir(directory).filePath(orbital.name);
      widget.set_definition(definition);
      application.processEvents();
      // Force the first upload before checking the renderer's status.
      widget.capture_frame();
      if (!widget.renderer_available()) {
        qCritical().noquote() << orbital.name << widget.renderer_error();
        return 1;
      }
      if (!write_atlas_file(stem + QStringLiteral(".uilorb"), bytes)) return 1;
      for (const bool surface_only : {false, true}) {
        widget.resize(surface_only ? 1000 : 1600, 800);
        application.processEvents();
        const QImage poster = widget.capture_poster(surface_only);
        const QString layout =
            surface_only ? QStringLiteral("surface") : QStringLiteral("surface-contour");
        if (poster.isNull() || !poster.save(stem + "-" + layout + ".png")) return 1;
      }
      entries.append(QJsonObject{{"orbital", orbital.name},
                                 {"palette", palette},
                                 {"radial_nodes", orbital.n - orbital.l - 1},
                                 {"angular_nodes", orbital.l},
                                 {"plane", plane},
                                 {"cutaway", orbital.l == 0 && orbital.n > 1}});
    }
    qInfo().noquote() << "Rendered atlas:" << orbital.name;
  }
  if (!write_atlas_file(output.filePath("catalog.tex"), catalog) ||
      !write_atlas_file(
          output.filePath("manifest.json"),
          QJsonDocument(QJsonObject{{"version", 1},
                                    {"orbitals", 55},
                                    {"palettes", QJsonArray{"garnet_slate", "garnet_teal"}},
                                    {"layouts", QJsonArray{"surface", "surface-contour"}},
                                    {"entries", entries}})
              .toJson()))
    return 1;
  return 0;
}
}  // namespace

int main(int argc, char* argv[]) {
    QApplication application(argc, argv);
    const QStringList arguments = application.arguments();
    if (arguments.size() == 3 && arguments.at(1) == QStringLiteral("--atlas")) {
      return generate_atlas(application, arguments.at(2));
    }
    if (arguments.size() < 3) {
      qCritical(
          "usage: atomic_orbital_preview_generator OUTPUT_DIR INPUT.uilorb [...] | --atlas "
          "OUTPUT_DIR");
      return 2;
    }

    QDir output_directory(arguments.at(1));
    if (!output_directory.exists() && !QDir().mkpath(output_directory.absolutePath())) {
        qCritical("could not create preview output directory");
        return 2;
    }

    AtomicOrbitalWidget widget;
    widget.resize(1200, 540);
    int input_index = 2;
    int result = 0;
    std::function<void()> render_next;
    render_next = [&]() {
        if (input_index >= arguments.size()) {
            application.exit(result);
            return;
        }

        const QString input_path = arguments.at(input_index++);
        QFile input(input_path);
        if (!input.open(QIODevice::ReadOnly)) {
            qCritical().noquote() << "could not read" << input_path;
            result = 1;
            QTimer::singleShot(0, &application, render_next);
            return;
        }
        AtomicOrbitalDefinition definition;
        QString error;
        if (!parse_atomic_orbital(input.readAll(), &definition, &error)) {
            qCritical().noquote() << input_path << ':' << error;
            result = 1;
            QTimer::singleShot(0, &application, render_next);
            return;
        }

        widget.set_definition(definition);
        widget.show();
        QTimer::singleShot(600, &application, [&, input_path]() {
            if (!widget.renderer_available()) {
                qCritical().noquote() << input_path << ':' << widget.renderer_error();
                result = 1;
            } else {
                const QImage preview = widget.capture_frame();
                const QString output_path = output_directory.filePath(
                    QFileInfo(input_path).completeBaseName() + QStringLiteral(".png"));
                if (preview.isNull() || !preview.save(output_path, "PNG")) {
                    qCritical().noquote() << "could not write" << output_path;
                    result = 1;
                } else {
                    qInfo().noquote() << "wrote" << output_path;
                }
            }
            QTimer::singleShot(0, &application, render_next);
        });
    };

    QTimer::singleShot(0, &application, render_next);
    return application.exec();
}
