#include <QCoreApplication>
#include <QDataStream>
#include <QDebug>
#include <QFile>
#include <QHash>
#include <QTextStream>
#include <algorithm>
#include <cmath>

#include "orbital/atomic_orbital.hpp"
#include "orbital/symmetry_orbitals.hpp"

/** @brief Offline-only baker: generates compressed signed meshes for the fixed symmetry basis. */
int main(int argc, char** argv) {
  QCoreApplication application(argc, argv);
  if (application.arguments().size() != 2) return 2;
  QFile file(application.arguments().at(1));
  if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) return 1;
  QTextStream output(&file);
  output << "// Generated by symmetry_orbital_baker. Do not edit.\n"
            "static const char* const kBakedOrbitals[] = {\n";
  for (const auto& name : symmetry_orbital_names()) {
    AtomicOrbitalCatalogEntry entry;
    if (!resolve_atomic_orbital(name, &entry)) return 1;
    AtomicOrbitalDefinition definition;
    definition.orbital = name;
    definition.n = entry.n;
    definition.l = entry.l;
    definition.m = entry.m;
    definition.grid_size = 81;
    QString error;
    auto volume = build_atomic_orbital_volume(definition, &error);
    if (!volume.is_valid()) {
      qCritical() << error;
      return 1;
    }
    // Remove the Condon--Shortley sign for familiar positive x/y lobes.
    if (std::abs(entry.m) % 2) volume.positive_vertices.swap(volume.negative_vertices);
    float radius = 0;
    for (const auto* phase : {&volume.positive_vertices, &volume.negative_vertices}) {
      for (const auto& vertex : *phase) radius = std::max(radius, vertex.position.length());
    }
    QByteArray bytes;
    QDataStream stream(&bytes, QIODevice::WriteOnly);
    stream.setByteOrder(QDataStream::LittleEndian);
    stream.setFloatingPointPrecision(QDataStream::SinglePrecision);
    for (const auto* phase : {&volume.positive_vertices, &volume.negative_vertices}) {
      QHash<QByteArray, quint32> unique;
      QByteArray packed;
      QVector<quint32> indices;
      for (const auto& vertex : *phase) {
        const QVector3D p = vertex.position / radius;
        QByteArray key;
        QDataStream packed_stream(&key, QIODevice::WriteOnly);
        packed_stream.setByteOrder(QDataStream::LittleEndian);
        for (float value :
             {p.x(), p.y(), p.z(), vertex.normal.x(), vertex.normal.y(), vertex.normal.z()}) {
          packed_stream << qint16(std::lround(std::clamp(value, -1.0f, 1.0f) * 32767.0f));
        }
        if (!unique.contains(key)) {
          unique.insert(key, quint32(unique.size()));
          packed.append(key);
        }
        indices.push_back(unique.value(key));
      }
      stream << quint32(unique.size());
      stream.writeRawData(packed.constData(), packed.size());
      stream << quint32(indices.size());
      for (auto index : indices) stream << index;
    }
    const QByteArray encoded = qCompress(bytes, 9).toBase64();
    output << "  // " << name << ", isovalue " << volume.isovalue << ", radius (Bohr) " << radius
           << "\n";
    for (int offset = 0; offset < encoded.size(); offset += 100) {
      output << "  \"" << encoded.mid(offset, 100) << "\"\n";
    }
    output << ",\n";
    qInfo() << name << volume.positive_vertices.size() << volume.negative_vertices.size();
  }
  output << "};\n";
  return 0;
}
