#pragma once

#define UIL_LAUNCHER_PROGRESS_MESSAGE (WM_APP + 0x155)

#define UIL_LAUNCHER_STAGE_STARTING_VIEWER 1
#define UIL_LAUNCHER_STAGE_QT_RUNTIME_READY 2
#define UIL_LAUNCHER_STAGE_THEME_READY 3
#define UIL_LAUNCHER_STAGE_CONTROLLER_READY 4
#define UIL_LAUNCHER_STAGE_AUDIENCE_READY 5
#define UIL_LAUNCHER_STAGE_PRESENTER_READY 6
#define UIL_LAUNCHER_STAGE_CONNECTIONS_READY 7
#define UIL_LAUNCHER_STAGE_SHOWING_PRESENTER 8
#define UIL_LAUNCHER_STAGE_FIRST_PAINT_READY 9
